// layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google"; // Import Open Sans from Google Fonts
import "./globals.css";
import NavBar from "@/components/navBar";
import HamBar from "@/components/hamBar";
import Footer from "@/components/footer";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Open Sans font configuration
const openSans = Open_Sans({
  subsets: ["latin"], // Adjust subset if needed
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} antialiased overflow-x-hidden`}
      >
        <div className="hidden lg:block">
          <NavBar />
        </div>

        <div className="block  lg:hidden w-full">
          <HamBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
